spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrm
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming :
        physical-strategy : com.example.hrm.config.UpperCaseNamingStrategy
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect:
          storage_engine: innodb

  security:
    login-page: # 로그인 페이지 주소
      /err/login
    staticContents-url-patterns: # 기본 스웨거 접속 url
      /v3/api-docs/**
      , /swagger-ui/**
    permitAll-url-patterns: # 모든 접근 허용 url 목록
      /login
      , /authCheck

springdoc:
  packages-to-scan: com.example.hrm
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /api-docs
    csrf:
      enabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true